theme: jekyll-theme-cayman

title: "VTC âœŒï¸ğŸ«– ğŸŒŠ : Improving Video-Text Retrieval with User Comments"
url: "https://vtc-dataset.com"
show_downloads: true
github:
  code_url: "https://github.com/unitaryai/VTC"
  dataset_url: "https://github.com/unitaryai/VTC-dataset"
  explore_url: "https://unitaryai.github.io/vtc-paper/assets/dataset_explorer.html"


