theme: jekyll-theme-cayman

title: "VTC âœŒï¸ğŸ«– ğŸŒŠ : Video-Text Retrieval with User Comments"
url: "https://vtc-dataset.com"
show_downloads: true
github:
  paper_url: "https://arxiv.org/abs/2210.10820"
  dataset_url: "https://github.com/unitaryai/VTC-dataset"
  explore_url: "https://unitaryai.github.io/vtc-paper/assets/dataset_explorer.html"
  code_url: "https://github.com/unitaryai/VTC"
  demo_url: "https://huggingface.co/unitary"
